name: Manual Publish to Main

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Commit all changes
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
          git add -A
          git commit -m "Manual publish of changes" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
